sudo: false

language: java
jdk: oraclejdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ant

script:
  - cd solitaire
  - ant dir
  - ant compile
  - if [ `ls -1 lib/cards | wc -l` -ne 52 ]; then echo "lib/cards does not contain required 52 cards!"; exit 1; fi
  - if [ ! -f dest-client/ija-client.jar  ]; then echo "dest-client/ija-client.jar not found!";         exit 1; fi
